apiVersion: v1
kind: ConfigMap
metadata:
  name: oc-casc-bundle
data:
  bundle.yaml: |
    apiVersion: "1"
    id: "jenkins"
    description: "Bundle for Operation Center"
    version: "1.1"
    jcasc:
      - "jenkins.yaml"
    catalog:
      - "plugin-catalog.yaml"
    plugins:
      - "plugins.yaml"
    items:
      - "items.yaml"

  jenkins.yaml: |
    jenkins:
      systemMessage: "Operations center configured using CloudBees CasC"
      authorizationStrategy: "cloudBeesRoleBasedAccessControl"
    cloudBeesCasCServer:
      defaultBundle: "demo-bundle"
      disableRemoteValidation: false
      visibility: true
    masterprovisioning:
      kubernetes:
        disk: 5
    unclassified:
      bundleStorageService:
          activated: true
          bundles:
          - name: "demo-bundle"
            retriever:
              localFolderRetriever:
                localFolder: "/var/casc"
          pollingPeriod: 120
          purgeOnDeactivation: false
      cascAutoControllerProvisioning:
        duration: 60
        fireAndForget: true
        initialDelay: 120
        provisionControllerOnCreation: true
        timeout: 600
  
  plugin-catalog.yaml: |
    type: "plugin-catalog"
    version: "1" 
    name: "azure-plugin-catalog"
    displayName: "Azure Plugin Catalog"
    configurations:
    - description: Exported plugins
      includePlugins:
        azure-credentials:
          version: 254.v64da_8176c83a
        azure-keyvault:
          version: 193.vdc33a_680fef6
        azure-sdk:
          version: 132.v62b_48eb_6f32f

  plugins.yaml: |
    plugins:
    - id: azure-credentials
    - id: azure-keyvault
    - id: azure-sdk
    - id: ace-editor
    - id: antisamy-markup-formatter
    - id: apache-httpcomponents-client-4-api
    - id: authentication-tokens
    - id: aws-credentials
    - id: aws-java-sdk-ec2
    - id: aws-java-sdk-elasticbeanstalk
    - id: aws-java-sdk-minimal
    - id: blueocean-commons
    - id: blueocean-rest
    - id: bluesteel-cjoc
    - id: bouncycastle-api
    - id: caffeine-api
    - id: cloudbees-administrative-monitors
    - id: cloudbees-analytics
    - id: cloudbees-assurance
    - id: cloudbees-blueocean-default-theme
    - id: cloudbees-casc-client
    - id: cloudbees-casc-items-api
    - id: cloudbees-casc-items-commons
    - id: cloudbees-casc-items-server
    - id: cloudbees-casc-server
    - id: cloudbees-folder
    - id: cloudbees-folders-plus
    - id: cloudbees-jenkins-advisor
    - id: cloudbees-license
    - id: cloudbees-monitoring
    - id: cloudbees-platform-common
    - id: cloudbees-platform-data
    - id: cloudbees-plugin-usage
    - id: cloudbees-ssh-slaves
    - id: cloudbees-support
    - id: cloudbees-uc-data-api
    - id: cloudbees-unified-ui
    - id: cloudbees-update-center-plugin
    - id: command-launcher
    - id: credentials
    - id: credentials-binding
    - id: display-url-api
    - id: docker-commons
    - id: durable-task
    - id: handy-uri-templates-2-api
    - id: infradna-backup
    - id: instance-identity
    - id: ionicons-api
    - id: jackson2-api
    - id: jakarta-activation-api
    - id: jakarta-mail-api
    - id: javax-activation-api
    - id: javax-mail-api
    - id: jaxb
    - id: jdk-tool
    - id: jjwt-api
    - id: jquery3-api
    - id: kube-agent-management
    - id: kubernetes
    - id: kubernetes-client-api
    - id: kubernetes-credentials
    - id: ldap
    - id: mailer
    - id: mapdb-api
    - id: master-provisioning-core
    - id: master-provisioning-kubernetes
    - id: metrics
    - id: mina-sshd-api-common
    - id: mina-sshd-api-core
    - id: mina-sshd-api-scp
    - id: mina-sshd-api-sftp
    - id: nectar-license
    - id: nectar-rbac
    - id: node-iterator-api
    - id: oauth-credentials
    - id: okhttp-api
    - id: operations-center-agent
    - id: operations-center-clusterops
    - id: operations-center-context
    - id: operations-center-elasticsearch-provider
    - id: operations-center-jnlp-controller
    - id: operations-center-kubernetes-cloud
    - id: operations-center-license
    - id: operations-center-monitoring
    - id: operations-center-rbac
    - id: operations-center-server
    - id: operations-center-sso
    - id: operations-center-updatecenter
    - id: plain-credentials
    - id: pubsub-light
    - id: scm-api
    - id: script-security
    - id: snakeyaml-api
    - id: sse-gateway
    - id: ssh-credentials
    - id: sshd
    - id: structs
    - id: support-core
    - id: token-macro
    - id: trilead-api
    - id: unique-id
    - id: user-activity-monitoring
    - id: variant
    - id: workflow-api
    - id: workflow-durable-task-step
    - id: workflow-step-api
    - id: workflow-support

  items.yaml: |
    removeStrategy:
      rbac: SYNC
      items: NONE
    items:
      - kind: managedController
        name: DemoController
        configuration:
          kubernetes:
            allowExternalAgents: false
            terminationGracePeriodSeconds: 1200
            image: 'CloudBees CI - Managed Controller - 2.387.1.3'
            memory: 3072
            fsGroup: '1000'
            cpus: 1.0
            readinessTimeoutSeconds: 5
            livenessInitialDelaySeconds: 300
            readinessInitialDelaySeconds: 30
            clusterEndpointId: default
            disk: 10
            readinessFailureThreshold: 100
            livenessTimeoutSeconds: 10
            storageClassName: default
            domain: democontroller
            livenessPeriodSeconds: 10
            javaOptions: '-XshowSettings:vm -XX:+AlwaysPreTouch -XX:+UseG1GC -XX:+DisableExplicitGC -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication -Dhudson.slaves.NodeProvisioner.initialDelay=0'
            yaml: |-
              ---
              apiVersion: "apps/v1"
              kind: "StatefulSet"
              name: test
              spec:
                template:
                  spec:
                    containers:
                      - name: "jenkins"
                        env:
                          - name: "sp_clientid"
                            valueFrom:
                              secretKeyRef:
                                key: clientId
                                name: service-principal
                          - name: "sp_tenant"
                            valueFrom:
                              secretKeyRef:
                                key: tenantId
                                name: service-principal
                          - name: "sp_subscription"
                            valueFrom:
                              secretKeyRef:
                                key: subscriptionId
                                name: service-principal
                          - name: "sp_secret"
                            valueFrom:
                              secretKeyRef:
                                key: clientSecret
                                name: service-principal
        description: ''
        displayName: Demo Controller
        properties:
          - configurationAsCode:
              bundle: demo-bundle
          - sharedHeaderLabelOptIn:
              optIn: true
          - healthReporting:
              enabled: true
          - owner:
              delay: 5
              owners: ''
          - envelopeExtension:
              allowExceptions: false
          - sharedConfigurationOptOut:
              optOut: false