apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argo-cd
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.11.2
  destination:
    name: "in-cluster"
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
