apiVersion: v2
name: cloudbees-ci
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

dependencies:
  - name: cloudbees-core
    repository: https://public-charts.artifacts.cloudbees.com/repository/public/
    version: ~3.56.2
